subplot(1, 4, 1);
file = fopen('shark_thresholded.txt', 'r');
image_data = fscanf(file, '%d\n');
fclose(file);
image = reshape(image_data, 800, 480);
imshow(image);
title('Thresholded');

subplot(1, 4, 2);
file = fopen('shark_histogrammed.txt', 'r');
image_data = fscanf(file, '%d\n');
fclose(file);
image = reshape(image_data, 800, 480);
imshow(image);
title('Histogrammed');

subplot(1, 4, 3);
file = fopen('shark_cumulated.txt', 'r');
image_data = fscanf(file, '%d\n');
fclose(file);
image = reshape(image_data, 800, 480);
imshow(image);
title('Cumulated');

subplot(1, 4, 4);
file = fopen('shark_hist_displayed.txt', 'r');
image_data = fscanf(file, '%d\n');
fclose(file);
image = reshape(image_data, 800, 480);
imshow(image);
title('Histogram From HistogramDisplay.v');

figure;
subplot(2,1,1);
file = fopen('shark_hist.txt', 'r');
data = fscanf(file, '%d\n');
fclose(file);
bar(data);
title('Histogram from Histogram.v');

subplot(2, 1, 2);
image = rgb2gray(imread('shark.jpg'));
p = reshape(image, 800*480, 1);
hist(double(p), 255);
h = hist(double(p), 255);
title('Histogram generated by Matlab');

figure;
subplot(2,1,1);
file = fopen('shark_cumhist.txt', 'r');
data = fscanf(file, '%d\n');
fclose(file);
bar(data);
title('Cumulative Histogram from CumulativeHistogram.v');

subplot(2,1,2);
ch = cumsum(h);
bar(ch);
title('Cumulative Histogram generated by Matlab');


figure;
subplot(2, 1, 1);
file = fopen('shark_total_hist.txt', 'r');
data = fscanf(file, '%d\n');
fclose(file);
bar(data);
title('Histogram from Total\_Histogram.v');

subplot(2,1,2);
file = fopen('shark_total_cumhist.txt', 'r');
data = fscanf(file, '%d\n');
fclose(file);
bar(data);
title('Cumulative Histogram from Total\_Histogram.v');
